# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='model',
            new_name='url_name',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='app_label',
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drf_role.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
