# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_role', '0002_auto_20170727_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='access_type_name',
            field=models.CharField(default='READ', max_length=20),
        ),
    ]
